use std::sync::Arc;

use winit::{
  event::{DeviceEvent, DeviceId, WindowEvent},
  window::{Window, WindowId},
};

use crate::{pty::PtyHandle, window_handle::WindowHandle};

/// An event relating to windows or [`winit`].
#[derive(Debug)]
pub enum WindowingEvent {
  /// A [`winit`] event loop control flow event.
  EventLoop(WinitEventLoopEvent),
  /// A [`WindowEvent`] sent by [`winit`].
  Window(WindowId, WindowEvent),
  /// A [`DeviceEvent`] sent by [`winit`].
  Device(DeviceId, DeviceEvent),
  /// Completion of the
  /// [`EventLoopCommand::BuildWindow`](crate::executor::EventLoopCommand)
  /// command.
  WindowBuilt(Arc<Window>),
}

/// A [`winit`] event loop control flow event.
#[derive(Debug)]
pub enum WinitEventLoopEvent {
  /// The [`winit`] event loop was resumed.
  Resumed,
  /// The [`winit`] event loop was suspended.
  Suspended,
  /// The [`winit`] event loop has exited.
  Exiting,
}

/// An event.
#[derive(Debug)]
pub enum Event {
  /// The launching process has finished and the application has fully started.
  ApplicationStarted,
  /// An event relating to windows or [`winit`].
  Windowing(Box<WindowingEvent>),
  /// Completion of the
  /// [`WindowingCommand::SpawnRenderer`](crate::executor::WindowingCommand)
  /// command.
  RendererSpawned(WindowHandle),
  /// Completion of the [`Command::SpawnPty`](crate::executor::Command) command.
  PtySpawned(PtyHandle),
  /// The user requested for the application to exit.
  ExitRequested,
  /// Some component of the application has critically failed.
  CriticalFailure {
    /// A rich description of what failed and where in the application.
    message: String,
    /// The report generated by the error itself.
    error:   miette::Report,
  },
}
