[package]
name = "carbo"
version = "0.1.0"

edition = "2024"

[dependencies]
derive-debug = { version = "0.1" }
fontique = { version = "0.10" }
miette = { version = "7.6", features = [ "fancy" ] }
pollster = { version = "0.4" }
portable-pty = { version = "0.9" }
skrifa = { version = "0.43" }
tracing = { version = "0.1" }
tracing-perfetto = { version = "0.1", optional = true }
tracing-subscriber = { version = "0.3", features = [ "env-filter" ] }
vello = { version = "0.8" }
vt100 = { git = "https://github.com/johnbchron/vt100-rust" }
wgpu = { version = "28" }
winit = { version = "0.30" }

[features]
default = [  ]
profile = [ "dep:tracing-perfetto" ]

[lints]
workspace = true
